from app.models import db, environment, SCHEMA
from sqlalchemy.sql import text
from app.models.community_members import community_members


def seed_community_members():
    connection = db.engine.connect()

    data = [
        {"community_id":1, "user_id":1},
        {"community_id":2, "user_id":1},
        {"community_id":3, "user_id":1},
        {"community_id":4, "user_id":1},
        {"community_id":5, "user_id":1},
        {"community_id":6, "user_id":1},
        {"community_id":7, "user_id":1},
        {"community_id":8, "user_id":1},
        {"community_id":9, "user_id":1},
        {"community_id":10, "user_id":1},
        {"community_id":11, "user_id":1},
        {"community_id":12, "user_id":1},
        {"community_id":13, "user_id":1},
        {"community_id":14, "user_id":1},
        {"community_id":15, "user_id":1},
        {"community_id":16, "user_id":1},
        {"community_id":1, "user_id":2},
        {"community_id":2, "user_id":2},
        {"community_id":3, "user_id":2},
        {"community_id":4, "user_id":2},
        {"community_id":5, "user_id":2},
        {"community_id":6, "user_id":2},
        {"community_id":7, "user_id":2},
        {"community_id":8, "user_id":2},
        {"community_id":9, "user_id":2},
        {"community_id":10, "user_id":2},
        {"community_id":11, "user_id":2},
        {"community_id":12, "user_id":2},
        {"community_id":13, "user_id":2},
        {"community_id":14, "user_id":2},
        {"community_id":15, "user_id":2},
        {"community_id":16, "user_id":2},
        {"community_id":1, "user_id":3},
        {"community_id":2, "user_id":3},
        {"community_id":3, "user_id":3},
        {"community_id":4, "user_id":3},
        {"community_id":5, "user_id":3},
        {"community_id":6, "user_id":3},
        {"community_id":7, "user_id":3},
        {"community_id":8, "user_id":3},
        {"community_id":9, "user_id":3},
        {"community_id":10, "user_id":3},
        {"community_id":11, "user_id":3},
        {"community_id":12, "user_id":3},
        {"community_id":13, "user_id":3},
        {"community_id":14, "user_id":3},
        {"community_id":15, "user_id":3},
        {"community_id":16, "user_id":3},
        {"community_id":1, "user_id":4},
        {"community_id":2, "user_id":4},
        {"community_id":3, "user_id":4},
        {"community_id":4, "user_id":4},
        {"community_id":5, "user_id":4},
        {"community_id":6, "user_id":4},
        {"community_id":7, "user_id":4},
        {"community_id":8, "user_id":4},
        {"community_id":9, "user_id":4},
        {"community_id":10, "user_id":4},
        {"community_id":11, "user_id":4},
        {"community_id":12, "user_id":4},
        {"community_id":13, "user_id":4},
        {"community_id":14, "user_id":4},
        {"community_id":15, "user_id":4},
        {"community_id":16, "user_id":4},
        {"community_id":1, "user_id":5},
        {"community_id":2, "user_id":5},
        {"community_id":3, "user_id":5},
        {"community_id":4, "user_id":5},
        {"community_id":5, "user_id":5},
        {"community_id":6, "user_id":5},
        {"community_id":7, "user_id":5},
        {"community_id":8, "user_id":5},
        {"community_id":9, "user_id":5},
        {"community_id":10, "user_id":5},
        {"community_id":11, "user_id":5},
        {"community_id":12, "user_id":5},
        {"community_id":13, "user_id":5},
        {"community_id":14, "user_id":5},
        {"community_id":15, "user_id":5},
        {"community_id":16, "user_id":5},
        {"community_id":1, "user_id":6},
        {"community_id":2, "user_id":6},
        {"community_id":3, "user_id":6},
        {"community_id":4, "user_id":6},
        {"community_id":5, "user_id":6},
        {"community_id":6, "user_id":6},
        {"community_id":7, "user_id":6},
        {"community_id":8, "user_id":6},
        {"community_id":9, "user_id":6},
        {"community_id":10, "user_id":6},
        {"community_id":11, "user_id":6},
        {"community_id":12, "user_id":6},
        {"community_id":13, "user_id":6},
        {"community_id":14, "user_id":6},
        {"community_id":15, "user_id":6},
        {"community_id":16, "user_id":6},
        {"community_id":1, "user_id":7},
        {"community_id":2, "user_id":7},
        {"community_id":3, "user_id":7},
        {"community_id":4, "user_id":7},
        {"community_id":5, "user_id":7},
        {"community_id":6, "user_id":7},
        {"community_id":7, "user_id":7},
        {"community_id":8, "user_id":7},
        {"community_id":9, "user_id":7},
        {"community_id":10, "user_id":7},
        {"community_id":11, "user_id":7},
        {"community_id":12, "user_id":7},
        {"community_id":13, "user_id":7},
        {"community_id":14, "user_id":7},
        {"community_id":15, "user_id":7},
        {"community_id":16, "user_id":7},
        {"community_id":1, "user_id":8},
        {"community_id":2, "user_id":8},
        {"community_id":3, "user_id":8},
        {"community_id":4, "user_id":8},
        {"community_id":5, "user_id":8},
        {"community_id":6, "user_id":8},
        {"community_id":7, "user_id":8},
        {"community_id":8, "user_id":8},
        {"community_id":9, "user_id":8},
        {"community_id":10, "user_id":8},
        {"community_id":11, "user_id":8},
        {"community_id":12, "user_id":8},
        {"community_id":13, "user_id":8},
        {"community_id":14, "user_id":8},
        {"community_id":15, "user_id":8},
        {"community_id":16, "user_id":8},
        {"community_id":1, "user_id":9},
        {"community_id":2, "user_id":9},
        {"community_id":3, "user_id":9},
        {"community_id":4, "user_id":9},
        {"community_id":5, "user_id":9},
        {"community_id":6, "user_id":9},
        {"community_id":7, "user_id":9},
        {"community_id":8, "user_id":9},
        {"community_id":9, "user_id":9},
        {"community_id":10, "user_id":9},
        {"community_id":11, "user_id":9},
        {"community_id":12, "user_id":9},
        {"community_id":13, "user_id":9},
        {"community_id":14, "user_id":9},
        {"community_id":15, "user_id":9},
        {"community_id":16, "user_id":9},
        {"community_id":1, "user_id":10},
        {"community_id":2, "user_id":10},
        {"community_id":3, "user_id":10},
        {"community_id":4, "user_id":10},
        {"community_id":5, "user_id":10},
        {"community_id":6, "user_id":10},
        {"community_id":7, "user_id":10},
        {"community_id":8, "user_id":10},
        {"community_id":9, "user_id":10},
        {"community_id":10, "user_id":10},
        {"community_id":11, "user_id":10},
        {"community_id":12, "user_id":10},
        {"community_id":13, "user_id":10},
        {"community_id":14, "user_id":10},
        {"community_id":15, "user_id":10},
        {"community_id":16, "user_id":10},
        {"community_id":1, "user_id":11},
        {"community_id":2, "user_id":11},
        {"community_id":3, "user_id":11},
        {"community_id":4, "user_id":11},
        {"community_id":5, "user_id":11},
        {"community_id":6, "user_id":11},
        {"community_id":7, "user_id":11},
        {"community_id":8, "user_id":11},
        {"community_id":9, "user_id":11},
        {"community_id":10, "user_id":11},
        {"community_id":11, "user_id":11},
        {"community_id":12, "user_id":11},
        {"community_id":13, "user_id":11},
        {"community_id":14, "user_id":11},
        {"community_id":15, "user_id":11},
        {"community_id":16, "user_id":11},
        {"community_id":1, "user_id":12},
        {"community_id":2, "user_id":12},
        {"community_id":3, "user_id":12},
        {"community_id":4, "user_id":12},
        {"community_id":5, "user_id":12},
        {"community_id":6, "user_id":12},
        {"community_id":7, "user_id":12},
        {"community_id":8, "user_id":12},
        {"community_id":9, "user_id":12},
        {"community_id":10, "user_id":12},
        {"community_id":11, "user_id":12},
        {"community_id":12, "user_id":12},
        {"community_id":13, "user_id":12},
        {"community_id":14, "user_id":12},
        {"community_id":15, "user_id":12},
        {"community_id":16, "user_id":12},
        {"community_id":1, "user_id":13},
        {"community_id":2, "user_id":13},
        {"community_id":3, "user_id":13},
        {"community_id":4, "user_id":13},
        {"community_id":5, "user_id":13},
        {"community_id":6, "user_id":13},
        {"community_id":7, "user_id":13},
        {"community_id":8, "user_id":13},
        {"community_id":9, "user_id":13},
        {"community_id":10, "user_id":13},
        {"community_id":11, "user_id":13},
        {"community_id":12, "user_id":13},
        {"community_id":13, "user_id":13},
        {"community_id":14, "user_id":13},
        {"community_id":15, "user_id":13},
        {"community_id":16, "user_id":13},
        {"community_id":1, "user_id":14},
        {"community_id":2, "user_id":14},
        {"community_id":3, "user_id":14},
        {"community_id":4, "user_id":14},
        {"community_id":5, "user_id":14},
        {"community_id":6, "user_id":14},
        {"community_id":7, "user_id":14},
        {"community_id":8, "user_id":14},
        {"community_id":9, "user_id":14},
        {"community_id":10, "user_id":14},
        {"community_id":11, "user_id":14},
        {"community_id":12, "user_id":14},
        {"community_id":13, "user_id":14},
        {"community_id":14, "user_id":14},
        {"community_id":15, "user_id":14},
        {"community_id":16, "user_id":14}
    ]

    for member in data:
        connection.execute(community_members.insert(), member)

    connection.close()


# Uses a raw SQL query to TRUNCATE or DELETE the community_members table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_seed_community_members():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.community_members RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM community_members"))

    db.session.commit()
